name: Release package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.DEFINED_SDK_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build
      - run: npm publish --access public
